import { supabase } from '../lib/supabaseClient';
import { humanizeError } from './storageManager';

/**
 * Calls one of the database's command functions -- order_command,
 * workshop_command or stock_command.
 *
 * Each applies its whole change in one transaction against locked rows: stock
 * travels as a CHANGE rather than a total, nothing commits unless all of it
 * does, and a request id seen before replays its first answer instead of
 * running again. That last part is what makes "press it again because nothing
 * seemed to happen" safe when a response was lost rather than never sent.
 *
 * The functions raise messages written for a person; humanizeError passes
 * those through rather than replacing them with something generic.
 */
export async function runCommand(rpcName, action, data, requestId) {
  try {
    const result = await supabase.rpc(rpcName, {
      p_action: action,
      p_data: data,
      p_request_id: requestId,
    });
    if (result.error) {
      return {
        ok: false,
        code: result.error.code,
        retryable: !result.error.code || result.status >= 500,
        message: humanizeError(result.error, 'We could not save this change. Check the details and try again.'),
      };
    }
    if (!result.data) return { ok: false, retryable: true, message: 'No saved record was returned. Please retry.' };
    return { ok: true, data: result.data };
  } catch {
    return {
      ok: false,
      retryable: true,
      message: 'The save could not be confirmed. Retry to check the same request safely.',
    };
  }
}

export const orderCommand = (action, data, requestId) => runCommand('order_command', action, data, requestId);

/**
 * Keeps the exact first payload and request id while a response may have been
 * lost, for actions fired from buttons rather than from a form that holds its
 * own request id (see production/WorkshopForm).
 *
 * The same request id is reused only for the same action on the same record
 * with the same content. A different payload is a different request, and a
 * known rejection or a success releases the id.
 */
export function createCommandRunner(send = orderCommand) {
  const pending = new Map();
  return {
    clear: () => pending.clear(),
    async run(action, data) {
      const key = `${action}:${data.orderId}:${data.deliveryId ?? ''}`;
      // Regenerated by the click handler rather than typed by anybody.
      const signature = JSON.stringify(data, (field, value) => {
        if (field === 'refundedAt' || field === 'id') return undefined;
        if (field === 'stockCommittedAt') return Boolean(value);
        return value;
      });
      let request = pending.get(key);
      if (request?.inFlight) return { ok: false, message: 'This change is already being saved.' };
      if (request?.signature !== signature) {
        request = { signature, data: structuredClone(data), id: crypto.randomUUID() };
        pending.set(key, request);
      }
      request.inFlight = true;
      try {
        const result = await send(action, request.data, request.id);
        if (!result.retryable && pending.get(key) === request) pending.delete(key);
        return result;
      } finally {
        request.inFlight = false;
      }
    },
  };
}
